import type { PaperDefinition } from './papers';

const source = 'CBSE-style practice · 2025–26 pattern';

export const additionalPaperDefinitions: Record<string, PaperDefinition> = {
  Polynomials: {
    id: 'polynomials-01', chapter: 'Polynomials', chapterNumber: 2, paperNumber: '01', focus: 'Use zeroes, coefficient relations, the division algorithm and simple graph interpretation.',
    mcqs: [
      { number: 1, question: 'The degree of 7x⁴ − 3x² + 5 is', options: ['4', '3', '2', '7'] },
      { number: 2, question: 'A zero of p(x) = x − 5 is', options: ['−5', '0', '5', '1'] },
      { number: 3, question: 'The zeroes of x² − 5x + 6 are', options: ['1, 6', '2, 3', '−2, −3', '−1, −6'] },
      { number: 4, question: 'The sum of the zeroes of 2x² − 7x + 3 is', options: ['−7/2', '7/2', '3/2', '−3/2'] },
      { number: 5, question: 'The product of the zeroes of 2x² − 7x + 3 is', options: ['7/2', '−7/2', '3/2', '−3/2'] },
      { number: 6, question: 'If 2 is a zero of x² + kx − 6, then k equals', options: ['−1', '0', '1', '2'] },
      { number: 7, question: 'The remainder when x³ − 4x + 1 is divided by x − 2 is', options: ['0', '1', '2', '−1'] },
      { number: 8, question: 'If α and β are zeroes of x² + px + q, then α + β equals', options: ['p', '−p', 'q', '−q'] },
      { number: 9, question: 'A polynomial whose graph cuts the x-axis at two distinct points has', options: ['no real zero', 'one real zero', 'two real zeroes', 'three real zeroes'] },
      { number: 10, question: 'A monic quadratic polynomial with zeroes 3 and −2 is', options: ['x² + x − 6', 'x² − x − 6', 'x² − 5x + 6', 'x² + 5x + 6'] },
      { number: 11, question: 'If the sum and product of two zeroes are 4 and 3, the monic polynomial is', options: ['x² + 4x + 3', 'x² − 4x + 3', 'x² + 3x − 4', 'x² − 3x + 4'] },
      { number: 12, question: 'The maximum number of zeroes of a cubic polynomial is', options: ['1', '2', '3', '4'] },
      { number: 13, question: 'The number of real zeroes of x² + 1 is', options: ['0', '1', '2', '3'] },
      { number: 14, question: 'If a quadratic polynomial has equal zeroes, then for ax² + bx + c', options: ['b² − 4ac > 0', 'b² − 4ac = 0', 'b² − 4ac < 0', 'a + b + c = 0'] },
    ],
    assertions: [
      { number: 15, assertion: 'x − a is a factor of p(x) when p(a) = 0.', reason: 'This is the Factor Theorem.' },
      { number: 16, assertion: 'The sum of the zeroes of 3x² − 8x + 2 is 8/3.', reason: 'For ax² + bx + c, the sum of zeroes is b/a.' },
    ],
    written: {
      17: 'Find the zeroes of x² − 7x + 12 and verify the relations between the zeroes and coefficients.',
      18: 'Form a quadratic polynomial whose zeroes are 4 and −3.',
      19: 'Find the remainder when 2x³ − 3x² + 4x − 5 is divided by x + 2.',
      20: 'If one zero of 3x² − 8x + 2k is twice the other, find k.',
      21: 'Divide 2x³ + 3x² − 11x − 6 by x − 2 and verify the division algorithm.',
      22: 'Find a quadratic polynomial whose zeroes are the reciprocals of the zeroes of 2x² − 5x + 3.',
      23: ['For p(x) = x³ − 6x² + 11x − 6:', '(a) Show that x − 1 is a factor. (b) Factorise p(x) completely. (c) State all its zeroes.'],
      24: ['A rectangular garden has length (x + 3) m and breadth (x − 1) m. Its area is represented by p(x).', '(a) Write p(x). [1]', '(b) Find p(7). [1]', '(c) If the area is 45 m², find the positive value of x. [2]'],
    },
    questionSources: { 20: source, 23: source },
    caseStudy: 'A rectangular garden has length (x + 3) metres and breadth (x − 1) metres. Its area is represented by a polynomial p(x).',
  },
  'Pair of Linear Equations in Two Variables': {
    id: 'linear-equations-01', chapter: 'Pair of Linear Equations in Two Variables', chapterNumber: 3, paperNumber: '01', focus: 'Check consistency and solve pairs algebraically and through real-life situations.',
    mcqs: [
      { number: 1, question: 'The solution of x + y = 5 and x − y = 1 is', options: ['(2, 3)', '(3, 2)', '(4, 1)', '(1, 4)'] },
      { number: 2, question: 'The pair 2x + 3y = 7 and 4x + 6y = 14 has', options: ['one solution', 'no solution', 'infinitely many solutions', 'exactly two solutions'] },
      { number: 3, question: 'The pair x + 2y = 4 and 2x + 4y = 9 has', options: ['one solution', 'no solution', 'infinitely many solutions', 'solution (0, 2)'] },
      { number: 4, question: 'Two intersecting straight lines represent a pair having', options: ['no solution', 'one unique solution', 'infinitely many solutions', 'two solutions'] },
      { number: 5, question: 'For a₁x + b₁y + c₁ = 0 and a₂x + b₂y + c₂ = 0 to have no solution', options: ['a₁/a₂ ≠ b₁/b₂', 'a₁/a₂ = b₁/b₂ ≠ c₁/c₂', 'a₁/a₂ = b₁/b₂ = c₁/c₂', 'a₁ = a₂ = 0'] },
      { number: 6, question: 'If 3x + 2y = 12 and x = 2, then y equals', options: ['2', '3', '4', '5'] },
      { number: 7, question: 'The equation x + y = 7 has', options: ['no solution', 'one solution', 'two solutions', 'infinitely many solutions'] },
      { number: 8, question: 'If 2x + ky = 6 and 4x + 6y = 12 have infinitely many solutions, k is', options: ['2', '3', '4', '6'] },
      { number: 9, question: 'The x-coordinate of the intersection of x + y = 6 and x − y = 2 is', options: ['2', '3', '4', '5'] },
      { number: 10, question: 'A pair of coincident lines is', options: ['inconsistent', 'consistent with a unique solution', 'consistent with infinitely many solutions', 'always perpendicular'] },
      { number: 11, question: 'Which ordered pair satisfies 2x + 3y = 12?', options: ['(3, 2)', '(2, 3)', '(4, 2)', '(1, 4)'] },
      { number: 12, question: 'The graphical solution of a pair of equations is the point where the lines', options: ['meet the axes', 'intersect each other', 'are parallel', 'have equal slopes only'] },
      { number: 13, question: 'If x pens and y pencils cost ₹50, a possible linear equation is', options: ['x + y = 50', '5x + 2y = 50', 'xy = 50', 'x² + y² = 50'] },
      { number: 14, question: 'For 3x + 2ky = 2 and 2x + 5y + 1 = 0 to be non-parallel, k must satisfy', options: ['k = 15/4', 'k ≠ 15/4', 'k = 4/15', 'k = 0 only'], source: 'CBSE SQP 2025–26 · adapted' },
    ],
    assertions: [
      { number: 15, assertion: 'The pair x + y = 3 and 2x + 2y = 6 has infinitely many solutions.', reason: 'The second equation represents the same line as the first.' },
      { number: 16, assertion: 'Two parallel distinct lines have a unique common point.', reason: 'Their slopes are equal.' },
    ],
    written: {
      17: 'Solve: 2x + y = 7 and x − y = 2.',
      18: 'Determine whether 3x + 2y = 5 and 6x + 4y = 9 are consistent.',
      19: 'Find k so that kx + 3y = k − 3 and 12x + ky = k have infinitely many solutions.',
      20: 'Solve 2x + 3y = 13 and 3x − 2y = 4 by elimination.',
      21: 'The sum of two numbers is 27 and their difference is 5. Form and solve a pair of equations.',
      22: 'Five years ago, a mother was seven times as old as her daughter. Five years later, she will be three times as old. Find their present ages.',
      23: ['A fraction becomes 1/3 when 1 is subtracted from its numerator and becomes 1/2 when 1 is added to its denominator.', '(a) Form two linear equations. (b) Find the fraction.'],
      24: ['At a school fair, 2 adult tickets and 3 student tickets cost ₹390, while 3 adult tickets and 2 student tickets cost ₹410.', '(a) Form the equations. [1]', '(b) Find each ticket price. [2]', '(c) Find the cost of 4 adult and 5 student tickets. [1]'],
    }, caseStudy: 'A school fair sells adult and student tickets. Two adult tickets and three student tickets cost ₹390; three adult tickets and two student tickets cost ₹410.',
  },
  'Quadratic Equations': {
    id: 'quadratic-equations-01', chapter: 'Quadratic Equations', chapterNumber: 4, paperNumber: '01', focus: 'Identify, solve and interpret quadratic equations using factorisation and the quadratic formula.',
    mcqs: [
      { number: 1, question: 'Which is a quadratic equation?', options: ['x³ − 1 = 0', 'x² − 5x + 6 = 0', '1/x + 2 = 0', '2x + 3 = 0'] },
      { number: 2, question: 'The roots of x² − 9 = 0 are', options: ['3 only', '−3 only', '3 and −3', '9 and 1'] },
      { number: 3, question: 'The discriminant of 2x² − 3x + 1 is', options: ['1', '5', '−1', '9'] },
      { number: 4, question: 'If D > 0, a quadratic equation has', options: ['two distinct real roots', 'equal real roots', 'no real roots', 'one root only'] },
      { number: 5, question: 'The roots of x² − 5x + 6 = 0 are', options: ['1, 6', '2, 3', '−2, −3', '−1, −6'] },
      { number: 6, question: 'The equation x² + 4x + 4 = 0 has', options: ['roots 2, 2', 'roots −2, −2', 'no real roots', 'roots 4, 1'] },
      { number: 7, question: 'For x² + kx + 9 = 0 to have equal roots, k can be', options: ['3', '±6', '9', '±3'] },
      { number: 8, question: 'The sum of roots of 3x² − 7x + 2 = 0 is', options: ['−7/3', '7/3', '2/3', '−2/3'] },
      { number: 9, question: 'The product of roots of 3x² − 7x + 2 = 0 is', options: ['7/3', '−7/3', '2/3', '−2/3'] },
      { number: 10, question: 'Which equation has no real roots?', options: ['x² − 4 = 0', 'x² + 4x + 4 = 0', 'x² + x + 1 = 0', 'x² − x = 0'] },
      { number: 11, question: 'A root of 2x² − 5x + 2 = 0 is', options: ['2', '3', '−2', '−1/2'] },
      { number: 12, question: 'The quadratic formula is', options: ['(−b ± √(b² − 4ac))/2a', '(b ± √(b² + 4ac))/2a', '(−b ± √(b² + 4ac))/a', '(b ± √(b² − 4ac))/a'] },
      { number: 13, question: 'If one root of x² − 6x + k = 0 is 2, then k is', options: ['4', '8', '12', '16'] },
      { number: 14, question: 'The roots of x² − 2√2x + 2 = 0 are', options: ['real and distinct', 'real and equal', 'not real', 'integers'] },
    ],
    assertions: [
      { number: 15, assertion: 'x² + 2x + 1 = 0 has equal roots.', reason: 'Its discriminant is zero.' },
      { number: 16, assertion: '(x + 2)(x + 1) = x² + 2x + 3 is a quadratic equation.', reason: 'After simplification, it becomes x − 1 = 0.' },
    ],
    written: {
      17: 'Solve x² − 7x + 12 = 0 by factorisation.', 18: 'Find the nature of the roots of 3x² − 4x + 2 = 0.', 19: 'Solve 2x² − 5x − 3 = 0 using the quadratic formula.',
      20: 'Find k if x² + kx + 16 = 0 has equal roots.', 21: 'The product of two consecutive positive integers is 306. Find the integers.',
      22: 'A train travels 360 km at a uniform speed. If the speed were 5 km/h more, the journey would take 1 hour less. Find the original speed.',
      23: ['The area of a rectangular field is 528 m². Its length is 1 m more than twice its breadth.', '(a) Form the quadratic equation. (b) Find its dimensions.'],
      24: ['A ball is thrown upward and its height after t seconds is h = 20t − 5t².', '(a) Find the height after 1 second. [1]', '(b) When is the height 15 m? [2]', '(c) When does the ball return to the ground? [1]'],
    }, caseStudy: 'A ball is thrown vertically upward. Its height h metres after t seconds is modelled by h = 20t − 5t².',
  },
  'Arithmetic Progressions': {
    id: 'arithmetic-progressions-01', chapter: 'Arithmetic Progressions', chapterNumber: 5, paperNumber: '01', focus: 'Recognise APs and use nth-term and sum formulae in direct and contextual problems.',
    mcqs: [
      { number: 1, question: 'The common difference of 3, 7, 11, 15, … is', options: ['3', '4', '7', '11'] },
      { number: 2, question: 'The nth term of an AP is', options: ['a + nd', 'a + (n − 1)d', 'n(a + d)', 'a − (n + 1)d'] },
      { number: 3, question: 'The 10th term of 2, 5, 8, … is', options: ['27', '29', '30', '32'] },
      { number: 4, question: 'Which sequence is an AP?', options: ['1, 2, 4, 8', '2, 5, 8, 11', '1, 4, 9, 16', '3, 6, 12, 24'] },
      { number: 5, question: 'If a = 5 and d = −2, then a₄ is', options: ['−1', '1', '3', '7'] },
      { number: 6, question: 'The sum of the first n terms of an AP is', options: ['n/2[2a + (n − 1)d]', 'n(a + d)', '2a + nd', 'n/2(a + d)'] },
      { number: 7, question: 'The 20th term of 5, 9, 13, … is', options: ['77', '81', '85', '89'] },
      { number: 8, question: 'If the nth term is 4n − 1, the common difference is', options: ['−1', '1', '3', '4'] },
      { number: 9, question: 'The middle term of the AP 7, 10, …, 43 is', options: ['22', '25', '28', '31'] },
      { number: 10, question: 'The sum 1 + 2 + … + 20 is', options: ['190', '200', '210', '220'] },
      { number: 11, question: 'If aₙ = 3n + 2, then a₁ is', options: ['2', '3', '5', '6'] },
      { number: 12, question: 'The number of terms in 4, 9, 14, …, 99 is', options: ['18', '19', '20', '21'] },
      { number: 13, question: 'If the sum of first n natural numbers is 55, n is', options: ['5', '10', '11', '55'] },
      { number: 14, question: 'Three numbers in AP may be written as', options: ['a, ar, ar²', 'a − d, a, a + d', 'a, a², a³', 'a/d, a, ad'] },
    ],
    assertions: [
      { number: 15, assertion: 'The sequence 5, 5, 5, 5, … is an AP.', reason: 'Its common difference is 0.' },
      { number: 16, assertion: 'The nth term of 2, 5, 8, … is 3n − 1.', reason: 'Its first term is 2 and common difference is 2.' },
    ],
    written: {
      17: 'Find the 25th term of the AP 7, 11, 15, ….', 18: 'Which term of 5, 9, 13, … is 121?', 19: 'Find the sum of the first 30 multiples of 4.',
      20: 'Find the AP whose third term is 16 and seventh term is 32.', 21: 'How many terms of 18, 15, 12, … must be taken so that their sum is 45?',
      22: 'The sum of the first 7 terms of an AP is 49 and the sum of the first 17 terms is 289. Find the AP.',
      23: ['A man repays a loan in monthly instalments. The first instalment is ₹1,000 and each next instalment is ₹100 more.', '(a) Find the 12th instalment. (b) Find the total paid in 12 months.'],
      24: ['In an auditorium, the first row has 20 seats and each successive row has 2 more seats. There are 15 rows.', '(a) Seats in the 10th row. [1]', '(b) Seats in the last row. [1]', '(c) Total number of seats. [2]'],
    }, caseStudy: 'An auditorium has 20 seats in the first row. Every successive row has 2 more seats than the preceding row, and there are 15 rows.',
  },
  Triangles: {
    id: 'triangles-01', chapter: 'Triangles', chapterNumber: 6, paperNumber: '01', focus: 'Apply similarity criteria, the Basic Proportionality Theorem and area relations.',
    mcqs: [
      { number: 1, question: 'If two triangles are equiangular, they are', options: ['congruent always', 'similar', 'right triangles', 'isosceles'] },
      { number: 2, question: 'For similar triangles, corresponding sides are', options: ['equal always', 'proportional', 'perpendicular', 'parallel'] },
      { number: 3, question: 'If ΔABC ~ ΔDEF, then AB/DE equals', options: ['BC/EF', 'BC/DF', 'AC/EF', 'DE/AB'] },
      { number: 4, question: 'A line parallel to one side of a triangle divides the other two sides', options: ['equally', 'proportionally', 'perpendicularly', 'randomly'] },
      { number: 5, question: 'If the sides of two similar triangles are in ratio 2:3, their areas are in ratio', options: ['2:3', '4:9', '8:27', '3:2'] },
      { number: 6, question: 'Triangles with sides 3, 4, 5 and 6, 8, 10 are similar by', options: ['AAA', 'SAS', 'SSS', 'RHS only'] },
      { number: 7, question: 'In ΔABC, DE ∥ BC. If AD/DB = 2/3, then AE/EC is', options: ['3/2', '2/3', '2/5', '5/3'] },
      { number: 8, question: 'If ΔABC ~ ΔPQR and AB:PQ = 3:5, then area(ABC):area(PQR) is', options: ['3:5', '6:10', '9:25', '27:125'] },
      { number: 9, question: 'The similarity criterion using two proportional sides and included equal angle is', options: ['AAA', 'SAS', 'SSS', 'RHS'] },
      { number: 10, question: 'All congruent triangles are', options: ['similar', 'not similar', 'equiangular only', 'scalene'] },
      { number: 11, question: 'If corresponding altitudes of two similar triangles are 4:7, their sides are in ratio', options: ['16:49', '4:7', '2:√7', '7:4'] },
      { number: 12, question: 'If DE ∥ BC in ΔABC, then AD/AB equals', options: ['AE/AC', 'EC/AC', 'DE/AB', 'BC/DE'] },
      { number: 13, question: 'Two triangles with angles 40°, 60°, 80° are', options: ['similar', 'congruent always', 'not comparable', 'right angled'] },
      { number: 14, question: 'The ratio of perimeters of similar triangles equals the ratio of their', options: ['areas', 'corresponding sides', 'squared sides', 'angles'] },
    ],
    assertions: [
      { number: 15, assertion: 'Two equilateral triangles are always similar.', reason: 'Every angle of each triangle is 60°.' },
      { number: 16, assertion: 'If two triangles have equal areas, they must be similar.', reason: 'Areas of similar triangles are proportional to squares of corresponding sides.' },
    ],
    written: {
      17: 'In ΔABC, DE ∥ BC. If AD = 3 cm, DB = 2 cm and AE = 4.5 cm, find EC.', 18: 'The sides of two similar triangles are in ratio 4:7. Find the ratio of their areas.',
      19: 'State and prove the converse of the Basic Proportionality Theorem.', 20: 'In ΔABC and ΔDEF, ∠A = ∠D, ∠B = ∠E, AB = 6 cm, DE = 9 cm and BC = 8 cm. Find EF.',
      21: 'The areas of two similar triangles are 64 cm² and 121 cm². If a side of the first is 16 cm, find the corresponding side of the second.',
      22: 'In a right triangle, the altitude from the right angle divides the hypotenuse into segments of 9 cm and 16 cm. Find the altitude.',
      23: ['In ΔABC, D and E lie on AB and AC with DE ∥ BC. AD = 4 cm, DB = 6 cm and AC = 15 cm.', '(a) Prove ΔADE ~ ΔABC. (b) Find AE and DE/BC.'],
      24: ['A 1.5 m pole casts a 2 m shadow while a tree casts a 12 m shadow at the same time.', '(a) Why are the triangles similar? [1]', '(b) Write the proportional relation. [1]', '(c) Find the height of the tree. [2]'],
    }, caseStudy: 'At the same instant, a 1.5 m pole casts a 2 m shadow and a nearby tree casts a 12 m shadow on level ground.',
  },
  'Coordinate Geometry': {
    id: 'coordinate-geometry-01', chapter: 'Coordinate Geometry', chapterNumber: 7, paperNumber: '01', focus: 'Use distance, section and midpoint formulae and determine areas from coordinates.',
    mcqs: [
      { number: 1, question: 'The distance of (2, 3) from the y-axis is', options: ['2', '3', '5', '1'], source: 'CBSE SQP 2025–26 · Q2' },
      { number: 2, question: 'The distance between (0, 0) and (3, 4) is', options: ['3', '4', '5', '7'] },
      { number: 3, question: 'The midpoint of (2, 5) and (6, 1) is', options: ['(4, 3)', '(8, 6)', '(2, 2)', '(3, 4)'] },
      { number: 4, question: 'The point dividing (0, 0) and (6, 9) in ratio 1:2 internally is', options: ['(2, 3)', '(4, 6)', '(3, 4.5)', '(1, 2)'] },
      { number: 5, question: 'The distance of (−5, 2) from the y-axis is', options: ['−5', '5', '2', '√29'] },
      { number: 6, question: 'The distance of (4, −7) from the x-axis is', options: ['4', '−7', '7', '√65'] },
      { number: 7, question: 'Which point lies on the x-axis?', options: ['(0, 5)', '(5, 0)', '(2, 3)', '(−1, 4)'] },
      { number: 8, question: 'The point equidistant from (2, 0) and (−2, 0) lies on the', options: ['x-axis only', 'y-axis', 'line x = 2', 'line y = 2'] },
      { number: 9, question: 'The area of a triangle with collinear vertices is', options: ['1 sq unit', '0', 'undefined', 'negative'] },
      { number: 10, question: 'The distance between (a, 0) and (0, b) is', options: ['a + b', 'a − b', '√(a² + b²)', 'ab'] },
      { number: 11, question: 'The centroid of a triangle with vertices (0,0), (6,0), (0,3) is', options: ['(2,1)', '(3,1)', '(2,3)', '(1,2)'] },
      { number: 12, question: 'The midpoint of (−3, 7) and (5, −1) is', options: ['(1,3)', '(2,4)', '(−4,8)', '(4,−2)'] },
      { number: 13, question: 'If P(x, 0) is equidistant from (2, 3) and (−2, 3), then x is', options: ['−2', '0', '2', '3'] },
      { number: 14, question: 'The points (1,2), (2,4), (3,6) are', options: ['vertices of an equilateral triangle', 'collinear', 'on the x-axis', 'on the y-axis'] },
    ],
    assertions: [
      { number: 15, assertion: 'The midpoint of a line segment is equidistant from both endpoints.', reason: 'It divides the segment internally in the ratio 1:1.' },
      { number: 16, assertion: 'The distance between (a, b) and (b, a) is always zero.', reason: 'The distance formula gives √2|a − b| for these points.' },
    ],
    written: {
      17: 'Find the distance between A(−2, 3) and B(4, −5).', 18: 'Find the midpoint of the segment joining (−7, 6) and (3, −4).', 19: 'Find the point dividing A(2, −3) and B(8, 9) internally in the ratio 1:2.',
      20: 'Show that the points (−2, 3), (2, −1) and (6, −5) are collinear.', 21: 'Find the area of the triangle with vertices (2, 3), (−1, 0) and (4, 0).',
      22: 'Find the value of k if (3, k), (5, 4) and (7, 6) are collinear.',
      23: ['A(−4, 0), B(4, 0) and C(0, 6) form a triangle.', '(a) Find AB, BC and CA. (b) Name the triangle. (c) Find its area.'],
      24: ['Three metro stations are A(0,0), B(6,0) and C(6,8), with coordinates measured in kilometres.', '(a) Find AB. [1]', '(b) Find BC. [1]', '(c) Find the direct distance AC and the distance saved by travelling directly. [2]'],
    }, caseStudy: 'On a city map, three metro stations have coordinates A(0, 0), B(6, 0) and C(6, 8), measured in kilometres.',
  },
  'Introduction to Trigonometry': {
    id: 'introduction-trigonometry-01', chapter: 'Introduction to Trigonometry', chapterNumber: 8, paperNumber: '01', focus: 'Use trigonometric ratios, standard values, complementary angles and identities.',
    mcqs: [
      { number: 1, question: 'In a right triangle, sin θ equals', options: ['base/hypotenuse', 'perpendicular/hypotenuse', 'perpendicular/base', 'hypotenuse/base'] },
      { number: 2, question: 'tan 45° equals', options: ['0', '1/√3', '1', '√3'] },
      { number: 3, question: 'sin 30° equals', options: ['0', '1/2', '1/√2', '√3/2'] },
      { number: 4, question: 'cos 60° equals', options: ['1/2', '1/√2', '√3/2', '1'] },
      { number: 5, question: 'sec²θ − tan²θ equals', options: ['0', '1', 'sin²θ', 'cos²θ'] },
      { number: 6, question: 'If sin θ = 3/5 for acute θ, cos θ is', options: ['3/4', '4/5', '5/4', '2/5'] },
      { number: 7, question: 'cosec θ is the reciprocal of', options: ['cos θ', 'tan θ', 'sin θ', 'cot θ'] },
      { number: 8, question: 'sin(90° − θ) equals', options: ['sin θ', 'cos θ', 'tan θ', 'cot θ'] },
      { number: 9, question: 'If tan θ = 1/√3, θ equals', options: ['30°', '45°', '60°', '90°'] },
      { number: 10, question: 'For acute θ, which value is impossible for sin θ?', options: ['0.2', '0.5', '1/√2', '1.2'] },
      { number: 11, question: 'If sec θ + tan θ = x, then sec θ − tan θ equals', options: ['x', '1/x', 'x²', '1 − x'], source: 'CBSE SQP 2025–26 · adapted' },
      { number: 12, question: 'cot 60° equals', options: ['√3', '1', '1/√3', '0'] },
      { number: 13, question: 'sin²45° + cos²45° equals', options: ['0', '1/2', '1', '2'] },
      { number: 14, question: 'If cos A = sin 35° for acute A, then A is', options: ['35°', '45°', '55°', '65°'] },
    ],
    assertions: [
      { number: 15, assertion: 'sin²θ + cos²θ = 1 for every acute θ.', reason: 'It follows from the Pythagorean theorem after dividing by the square of the hypotenuse.' },
      { number: 16, assertion: 'tan θ is defined when θ = 90°.', reason: 'cos 90° = 0 and tan θ = sin θ/cos θ.' },
    ],
    written: {
      17: 'If sin A = 5/13, find cos A and tan A.', 18: 'Evaluate: 2 sin 30° cos 60° + tan 45°.', 19: 'Prove that (1 − sin²A)/cos²A = 1.',
      20: 'If tan A = 3/4, evaluate (sin A + cos A)/(sin A − cos A).', 21: 'Prove that (sec A − tan A)(sec A + tan A) = 1.',
      22: 'If sin(A + B) = 1 and cos(A − B) = √3/2, where A and B are acute, find A and B.',
      23: ['Prove: (1 + tan²A)/(1 + cot²A) = tan²A.', 'Hence evaluate the expression for A = 45°.'],
      24: ['A right-triangular ramp has base 12 m and height 5 m.', '(a) Find the hypotenuse. [1]', '(b) Find sin θ and cos θ for the angle θ at the lower end. [2]', '(c) Verify sin²θ + cos²θ = 1. [1]'],
    }, caseStudy: 'A right-triangular accessibility ramp has a horizontal base of 12 m and a vertical height of 5 m. Let θ be the angle the ramp makes with the ground.',
  },
  Circles: {
    id: 'circles-01', chapter: 'Circles', chapterNumber: 10, paperNumber: '01', focus: 'Apply tangent theorems and properties of radii, chords and external points.',
    mcqs: [
      { number: 1, question: 'A tangent to a circle intersects it at', options: ['no point', 'one point', 'two points', 'three points'] },
      { number: 2, question: 'The radius through the point of contact is', options: ['parallel to the tangent', 'perpendicular to the tangent', 'equal to the tangent', 'a chord'] },
      { number: 3, question: 'Tangents drawn from an external point to a circle are', options: ['unequal', 'equal in length', 'parallel', 'perpendicular'] },
      { number: 4, question: 'The number of tangents from a point inside a circle is', options: ['0', '1', '2', 'infinite'] },
      { number: 5, question: 'The number of tangents from a point on a circle is', options: ['0', '1', '2', 'infinite'] },
      { number: 6, question: 'The number of tangents from a point outside a circle is', options: ['0', '1', '2', '3'] },
      { number: 7, question: 'If PA and PB are tangents from P and PA = 8 cm, PB is', options: ['4 cm', '8 cm', '16 cm', 'cannot be found'] },
      { number: 8, question: 'If OP = 13 cm and radius = 5 cm, tangent length from P is', options: ['8 cm', '12 cm', '13 cm', '18 cm'] },
      { number: 9, question: 'The angle between a radius and tangent at contact is', options: ['30°', '45°', '60°', '90°'] },
      { number: 10, question: 'If two tangents PA and PB make an angle 60° at P, ∠AOB is', options: ['60°', '90°', '120°', '180°'] },
      { number: 11, question: 'A line meeting a circle at two points is a', options: ['tangent', 'secant', 'radius', 'diameter only'] },
      { number: 12, question: 'In quadrilateral OAPB formed by two tangents, ∠OAP equals', options: ['0°', '45°', '90°', '180°'] },
      { number: 13, question: 'If ∠APB = 70°, then central angle ∠AOB is', options: ['70°', '90°', '110°', '140°'] },
      { number: 14, question: 'The centre of a circle lies on the', options: ['tangent at every point', 'perpendicular to tangent at contact', 'tangent segment', 'secant outside circle'] },
    ],
    assertions: [
      { number: 15, assertion: 'Tangents from the same external point are equal.', reason: 'The two right triangles formed with the centre are congruent by RHS.' },
      { number: 16, assertion: 'A tangent can pass through the centre of a circle.', reason: 'A tangent is perpendicular to the radius at the point of contact.' },
    ],
    written: {
      17: 'From external point P, PA and PB are tangents. If PA = 7.5 cm, find PB.', 18: 'A tangent PQ at Q to a circle of radius 5 cm has OP = 13 cm. Find PQ.',
      19: 'Prove that the tangent at any point of a circle is perpendicular to the radius through the point of contact.',
      20: 'Two tangents PA and PB from P make an angle of 80°. Find ∠AOB, where O is the centre.',
      21: 'A quadrilateral ABCD circumscribes a circle. Prove that AB + CD = AD + BC.',
      22: 'Two concentric circles have radii 5 cm and 13 cm. Find the length of a chord of the larger circle tangent to the smaller circle.',
      23: ['From P, tangents PA and PB touch a circle with centre O. OP = 10 cm and radius = 6 cm.', '(a) Find PA. (b) Prove OP bisects ∠APB.'],
      24: ['A circular park has centre O. From an external point P, two paths PA and PB touch the park at A and B. OP = 25 m and radius = 7 m.', '(a) State ∠OAP. [1]', '(b) Find PA. [2]', '(c) Compare PA and PB. [1]'],
    }, caseStudy: 'A circular park has centre O and radius 7 m. From an external point P, 25 m from O, two straight paths PA and PB touch the park.',
  },
  'Areas Related to Circles': {
    id: 'areas-circles-01', chapter: 'Areas Related to Circles', chapterNumber: 11, paperNumber: '01', focus: 'Calculate circumference, sector, arc and segment measures in combined figures.',
    mcqs: [
      { number: 1, question: 'The circumference of a circle of radius r is', options: ['πr²', '2πr', 'πr', '2πr²'] },
      { number: 2, question: 'The area of a circle of radius 7 cm using π = 22/7 is', options: ['44 cm²', '77 cm²', '154 cm²', '308 cm²'] },
      { number: 3, question: 'The area of a 90° sector is what fraction of the circle?', options: ['1/2', '1/3', '1/4', '1/6'] },
      { number: 4, question: 'Arc length of a 60° sector of radius 21 cm is', options: ['11 cm', '22 cm', '33 cm', '44 cm'] },
      { number: 5, question: 'The perimeter of a semicircle of radius r is', options: ['πr', 'πr + 2r', '2πr', 'πr²/2'] },
      { number: 6, question: 'Area of a sector of angle θ is', options: ['θ/360 × πr²', 'θ/180 × πr²', '360/θ × πr²', '2πrθ'] },
      { number: 7, question: 'A quadrant has central angle', options: ['45°', '90°', '180°', '360°'] },
      { number: 8, question: 'The area of a minor segment equals', options: ['sector + triangle', 'sector − triangle', 'circle − sector', 'arc × radius'] },
      { number: 9, question: 'If radius doubles, the area becomes', options: ['double', 'triple', 'four times', 'eight times'] },
      { number: 10, question: 'The circumference of a wheel of diameter 70 cm is', options: ['110 cm', '220 cm', '440 cm', '1540 cm'] },
      { number: 11, question: 'The area of a semicircle of radius 14 cm is', options: ['154 cm²', '308 cm²', '616 cm²', '1232 cm²'] },
      { number: 12, question: 'A sector with angle 180° is a', options: ['quadrant', 'semicircle', 'minor segment', 'full circle'] },
      { number: 13, question: 'The area between two concentric circles is', options: ['π(R² − r²)', '2π(R − r)', 'π(R − r)²', 'π(R² + r²)'] },
      { number: 14, question: 'For fixed arc length, increasing radius makes the central angle', options: ['increase', 'decrease', 'unchanged', '360°'] },
    ],
    assertions: [
      { number: 15, assertion: 'The area of a sector is proportional to its central angle.', reason: 'A 360° sector is the entire circle.' },
      { number: 16, assertion: 'Doubling a circle’s radius doubles its area.', reason: 'Area equals πr².' },
    ],
    written: {
      17: 'Find the area and circumference of a circle of radius 10.5 cm.', 18: 'Find the area of a 120° sector of a circle of radius 7 cm.', 19: 'Find the length of an arc subtending 60° at the centre of a circle of radius 21 cm.',
      20: 'Find the area of the minor segment of a circle of radius 14 cm cut off by a chord subtending 90° at the centre.',
      21: 'A wheel of radius 35 cm makes 200 revolutions. Find the distance travelled in metres.',
      22: 'A circular garden of radius 14 m is surrounded by a 3.5 m wide path. Find the area of the path.',
      23: ['A square of side 14 cm contains four quadrants of radius 7 cm, one at each corner.', '(a) Find the total area of the quadrants. (b) Find the unshaded area inside the square.'],
      24: ['A sprinkler waters a sector of radius 21 m through an angle of 120°.', '(a) Find the arc length. [2]', '(b) Find the watered area. [2]'],
    }, caseStudy: 'A rotating sprinkler waters a sector of a circular lawn. Its range is 21 m and it turns through an angle of 120°.',
  },
  'Surface Areas and Volumes': {
    id: 'surface-areas-volumes-01', chapter: 'Surface Areas and Volumes', chapterNumber: 12, paperNumber: '01', focus: 'Use surface-area and volume formulae for cylinders, cones, spheres and combinations.',
    mcqs: [
      { number: 1, question: 'The curved surface area of a cylinder is', options: ['πr²h', '2πrh', '2πr(r + h)', 'πrl'] },
      { number: 2, question: 'The volume of a cone is', options: ['πr²h', '1/2πr²h', '1/3πr²h', '4/3πr³'] },
      { number: 3, question: 'The surface area of a sphere is', options: ['πr²', '2πr²', '3πr²', '4πr²'] },
      { number: 4, question: 'The volume of a sphere is', options: ['4πr²', '4/3πr³', '2/3πr³', 'πr²h'] },
      { number: 5, question: 'The slant height of a cone is', options: ['√(r² + h²)', 'r + h', 'r² + h²', '√(h² − r²) always'] },
      { number: 6, question: 'A hemisphere’s curved surface area is', options: ['πr²', '2πr²', '3πr²', '4πr²'] },
      { number: 7, question: 'The total surface area of a hemisphere is', options: ['2πr²', '3πr²', '4πr²', 'πr²'] },
      { number: 8, question: 'If all dimensions are doubled, volume becomes', options: ['2 times', '4 times', '6 times', '8 times'] },
      { number: 9, question: '1 litre equals', options: ['10 cm³', '100 cm³', '1000 cm³', '10000 cm³'] },
      { number: 10, question: 'A cylinder and cone have the same base and height. Their volume ratio is', options: ['1:1', '2:1', '3:1', '1:3'] },
      { number: 11, question: 'The radius of a sphere with diameter 14 cm is', options: ['3.5 cm', '7 cm', '14 cm', '28 cm'] },
      { number: 12, question: 'The curved surface area of a cone is', options: ['πr²', 'πrl', '2πrh', 'πr(r + l)'] },
      { number: 13, question: 'A solid melted and recast has unchanged', options: ['surface area', 'shape', 'volume', 'height'] },
      { number: 14, question: 'The ratio of volumes of spheres with radii 2:3 is', options: ['2:3', '4:9', '8:27', '16:81'] },
    ],
    assertions: [
      { number: 15, assertion: 'When a solid is melted and recast, its volume remains unchanged.', reason: 'No material is added or removed.' },
      { number: 16, assertion: 'A cylinder and cone with equal base and height have equal volumes.', reason: 'The cone’s volume is one-third of the cylinder’s volume.' },
    ],
    written: {
      17: 'Find the curved surface area of a cylinder of radius 7 cm and height 10 cm.', 18: 'A cone has radius 6 cm and height 8 cm. Find its slant height and curved surface area.',
      19: 'Find the volume of a sphere of radius 3.5 cm.', 20: 'A solid consists of a hemisphere surmounted by a cone, both of radius 3 cm. If the cone height is 4 cm, find the total volume.',
      21: 'A metallic sphere of radius 6 cm is melted into small spheres of radius 2 cm. Find the number of small spheres.',
      22: 'A cylindrical tank of radius 1.4 m and height 3 m is filled with water. Find its capacity in litres.',
      23: ['A toy is in the form of a cone mounted on a hemisphere. The common radius is 7 cm and cone height is 24 cm.', '(a) Find the slant height. (b) Find the exposed surface area.'],
      24: ['A cylindrical glass has internal radius 3.5 cm and height 12 cm.', '(a) Find its capacity. [2]', '(b) How many full glasses fill a 4.62 litre container? [2]'],
    }, caseStudy: 'A cylindrical drinking glass has internal radius 3.5 cm and height 12 cm. A water container holds 4.62 litres.',
  },
  Statistics: {
    id: 'statistics-01', chapter: 'Statistics', chapterNumber: 13, paperNumber: '01', focus: 'Calculate mean, median and mode of grouped data and interpret cumulative frequencies.',
    mcqs: [
      { number: 1, question: 'The class mark of 10–20 is', options: ['10', '15', '20', '30'] },
      { number: 2, question: 'The mean of 2, 4, 6, 8 is', options: ['4', '5', '6', '20'] },
      { number: 3, question: 'The median class contains the', options: ['first observation', 'N/2th observation', 'last observation', 'highest frequency only'] },
      { number: 4, question: 'The modal class has the', options: ['lowest frequency', 'highest frequency', 'middle class mark', 'largest width'] },
      { number: 5, question: 'The empirical relation is', options: ['Mode = 3 Median − 2 Mean', 'Mean = 3 Mode − 2 Median', 'Median = 3 Mean − 2 Mode', 'Mode = Mean + Median'] },
      { number: 6, question: 'Cumulative frequency is found by', options: ['multiplying frequencies', 'successive addition', 'successive subtraction', 'dividing by class size'] },
      { number: 7, question: 'If every observation increases by 5, the mean', options: ['decreases by 5', 'increases by 5', 'is unchanged', 'doubles'] },
      { number: 8, question: 'The sum of all frequencies is denoted by', options: ['xᵢ', 'fᵢ', 'N', 'h'] },
      { number: 9, question: 'For class interval 20–30, lower limit is', options: ['10', '20', '25', '30'] },
      { number: 10, question: 'If mean = 20 and median = 22, empirical mode is', options: ['18', '24', '26', '28'] },
      { number: 11, question: 'The median of 3, 5, 7, 9, 11 is', options: ['5', '7', '8', '9'] },
      { number: 12, question: 'The assumed mean method is useful mainly to', options: ['change the data', 'simplify calculations', 'find class width only', 'remove frequencies'] },
      { number: 13, question: 'An ogive represents', options: ['raw observations only', 'cumulative frequency', 'class marks only', 'mode only'] },
      { number: 14, question: 'The median of an even number of ungrouped observations is', options: ['always one observation', 'average of two middle observations', 'the mode', 'the range'] },
    ],
    assertions: [
      { number: 15, assertion: 'The sum of deviations from the arithmetic mean is zero.', reason: 'The mean balances the observations algebraically.' },
      { number: 16, assertion: 'The modal class always contains the N/2th observation.', reason: 'The modal class has the greatest frequency.' },
    ],
    written: {
      17: 'Find the mean of 8, 12, 15, 10 and 5.', 18: 'Find the median of 7, 3, 9, 12, 5, 8 and 6.', 19: 'The mean of five numbers is 18. If four numbers are 12, 17, 20 and 25, find the fifth.',
      20: 'Find the mean of the distribution: x: 10, 20, 30, 40; f: 3, 5, 4, 2.',
      21: 'Find the median for classes 0–10, 10–20, 20–30, 30–40 with frequencies 5, 9, 12, 4.',
      22: 'Find the mode for classes 10–20, 20–30, 30–40, 40–50 with frequencies 4, 9, 15, 7.',
      23: ['The marks of 40 students are grouped as 0–10: 5, 10–20: 8, 20–30: 15, 30–40: 8, 40–50: 4.', '(a) Find cumulative frequencies. (b) Find the median.'],
      24: ['Daily study time of students is grouped as 0–1 h: 4, 1–2 h: 8, 2–3 h: 12, 3–4 h: 6.', '(a) Total students. [1]', '(b) Modal class. [1]', '(c) Mean study time using class marks. [2]'],
    }, caseStudy: 'A teacher records daily study time: 0–1 hour: 4 students, 1–2: 8, 2–3: 12 and 3–4: 6.',
  },
  Probability: {
    id: 'probability-01', chapter: 'Probability', chapterNumber: 14, paperNumber: '01', focus: 'Use equally likely outcomes, complements and simple experiments with coins, dice and cards.',
    mcqs: [
      { number: 1, question: 'The probability of a sure event is', options: ['0', '1/2', '1', '2'] },
      { number: 2, question: 'The probability of an impossible event is', options: ['0', '1/4', '1/2', '1'] },
      { number: 3, question: 'For any event E, P(E) lies between', options: ['−1 and 1', '0 and 1', '1 and 2', '−∞ and ∞'] },
      { number: 4, question: 'When a fair coin is tossed, P(head) is', options: ['0', '1/4', '1/2', '1'] },
      { number: 5, question: 'When a die is rolled, P(rolling 4) is', options: ['1/2', '1/3', '1/4', '1/6'] },
      { number: 6, question: 'The probability of an even number on a die is', options: ['1/6', '1/3', '1/2', '2/3'] },
      { number: 7, question: 'P(not E) equals', options: ['P(E)', '1 − P(E)', '1 + P(E)', '1/P(E)'] },
      { number: 8, question: 'The number of outcomes when two coins are tossed is', options: ['2', '3', '4', '8'] },
      { number: 9, question: 'From a deck of 52 cards, P(ace) is', options: ['1/52', '1/26', '1/13', '4/13'] },
      { number: 10, question: 'From a deck, P(red card) is', options: ['1/4', '1/2', '3/4', '1'] },
      { number: 11, question: 'A bag has 3 red and 2 blue balls. P(red) is', options: ['2/5', '3/5', '1/2', '3/2'] },
      { number: 12, question: 'On a die, P(number greater than 4) is', options: ['1/6', '1/3', '1/2', '2/3'] },
      { number: 13, question: 'If P(E) = 0.35, P(not E) is', options: ['0.35', '0.55', '0.65', '1.35'] },
      { number: 14, question: 'The sum of probabilities of all elementary outcomes is', options: ['0', '1/2', '1', 'depends on experiment'] },
    ],
    assertions: [
      { number: 15, assertion: 'The probability of an event can never exceed 1.', reason: 'Favourable outcomes cannot exceed the total equally likely outcomes.' },
      { number: 16, assertion: 'When two coins are tossed, getting exactly one head has probability 1/4.', reason: 'The outcomes HT and TH both have exactly one head.' },
    ],
    written: {
      17: 'A die is thrown once. Find the probability of getting a prime number.', 18: 'A card is drawn from a deck of 52 cards. Find the probability that it is a king.', 19: 'Two coins are tossed together. Find the probability of getting at least one head.',
      20: 'A bag contains 5 red, 7 white and 8 black balls. One ball is drawn. Find P(red), P(white) and P(not black).',
      21: 'A number is selected at random from 1 to 50. Find the probability that it is divisible by 5 or 7.',
      22: 'Two dice are thrown. Find the probability that the sum is 8.',
      23: ['Cards numbered 1 to 30 are mixed and one card is drawn.', '(a) Find P(multiple of 3). (b) Find P(prime number). (c) Find P(neither).'],
      24: ['A game wheel has 12 equal sectors numbered 1 to 12.', '(a) P(even number). [1]', '(b) P(multiple of 3). [1]', '(c) P(prime or multiple of 4). [2]'],
    }, caseStudy: 'A game wheel is divided into 12 equal sectors numbered 1 to 12. A fair spin stops on one sector.',
  },
};
